# Generated by Django 5.2.4 on 2026-08-11 14:26

import badge_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_code', models.CharField(default=badge_app.models.generate_unique_code, max_length=20, unique=True, verbose_name='رمز التسجيل')),
                ('full_name', models.CharField(max_length=150, verbose_name='الاسم الكامل')),
                ('role', models.CharField(default='متعلّمة', max_length=50, verbose_name='الصفة')),
                ('batch', models.CharField(blank=True, max_length=100, verbose_name='الدفعة')),
                ('year', models.CharField(default='٢٠٢٦', max_length=20, verbose_name='السنة')),
                ('class_name', models.CharField(blank=True, max_length=100, verbose_name='الصف')),
                ('course', models.CharField(blank=True, max_length=150, verbose_name='الدورة')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='participant_photos/', verbose_name='الصورة الشخصية')),
                ('badge_image', models.ImageField(blank=True, null=True, upload_to='badges/', verbose_name='صورة البطاقة')),
                ('qr_code_image', models.ImageField(blank=True, null=True, upload_to='qr_codes/', verbose_name='رمز QR')),
                ('is_verified', models.BooleanField(default=False, verbose_name='تم الحضور / التحقق')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت التحقق')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التسجيل')),
            ],
            options={
                'verbose_name': 'مشاركة',
                'verbose_name_plural': 'المشاركات',
                'ordering': ['-created_at'],
            },
        ),
    ]
